# Generated by Django 4.0.1 on 2022-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib_app', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
